CREATE DATABASE SNBTEST;

CREATE TABLE SNBTEST.SNB_BOARD (
BOARD_SEQ INT NOT NULL AUTO_INCREMENT,
TITLE VARCHAR(50) NOT NULL,
CONTENT VARCHAR(2000) NOT NULL,
DEL_YN VARCHAR(1) NOT NULL DEFAULT 'N' ,
INS_DATE DATETIME NOT NULL default current_timestamp,
UPD_DATE DATETIME NOT NULL default current_timestamp,
INS_USER VARCHAR(20) NOT NULL,
PRIMARY KEY (BOARD_SEQ)
);

CREATE TABLE SNBTEST.SNB_USER (
USERNAME VARCHAR(20) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
PRIMARY KEY (USERNAME)
);

CREATE TABLE SNBTEST.SNB_COMMENT (
COMMENT_SEQ INT NOT NULL AUTO_INCREMENT,
BOARD_SEQ INT NOT NULL,
COMMENT VARCHAR(1000) NOT NULL,
DEL_YN VARCHAR(1) NOT NULL DEFAULT 'N' ,
INS_DATE DATETIME NOT NULL default current_timestamp,
UPD_DATE DATETIME NOT NULL default current_timestamp,
INS_USER VARCHAR(20) NOT NULL,
PRIMARY KEY (COMMENT_SEQ)
);